// Complete CCSS ELA Standards K-5 extracted from official Common Core documents
export type CCSSDomain = 'RL' | 'RI' | 'RF' | 'W' | 'SL' | 'L'
export interface CcssStandard { code: string; domain: CCSSDomain; grade: number; cluster: string; text: string }

export const CCSS_DOMAINS: { key: CCSSDomain; label: string }[] = [
  { key: 'RL', label: 'Reading: Literature' },
  { key: 'RI', label: 'Reading: Informational' },
  { key: 'RF', label: 'Foundational Skills' },
  { key: 'W', label: 'Writing' },
  { key: 'SL', label: 'Speaking & Listening' },
  { key: 'L', label: 'Language' },
]

export const CCSS_STANDARDS: CcssStandard[] = [
  // ═══════════════ KINDERGARTEN (grade=0) ═══════════════
  // RL - Reading: Literature
  {code:'RL.K.1',domain:'RL',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, ask and answer questions about key details in a text.'},
  {code:'RL.K.2',domain:'RL',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, retell familiar stories, including key details.'},
  {code:'RL.K.3',domain:'RL',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, identify characters, settings, and major events in a story.'},
  {code:'RL.K.4',domain:'RL',grade:0,cluster:'Craft & Structure',text:'Ask and answer questions about unknown words in a text.'},
  {code:'RL.K.5',domain:'RL',grade:0,cluster:'Craft & Structure',text:'Recognize common types of texts (e.g., storybooks, poems).'},
  {code:'RL.K.6',domain:'RL',grade:0,cluster:'Craft & Structure',text:'With prompting and support, name the author and illustrator of a story and define the role of each in telling the story.'},
  {code:'RL.K.7',domain:'RL',grade:0,cluster:'Integration',text:'With prompting and support, describe the relationship between illustrations and the story in which they appear.'},
  {code:'RL.K.9',domain:'RL',grade:0,cluster:'Integration',text:'With prompting and support, compare and contrast the adventures and experiences of characters in familiar stories.'},
  {code:'RL.K.10',domain:'RL',grade:0,cluster:'Range',text:'Actively engage in group reading activities with purpose and understanding.'},
  // RI - Reading: Informational
  {code:'RI.K.1',domain:'RI',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, ask and answer questions about key details in a text.'},
  {code:'RI.K.2',domain:'RI',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, identify the main topic and retell key details of a text.'},
  {code:'RI.K.3',domain:'RI',grade:0,cluster:'Key Ideas & Details',text:'With prompting and support, describe the connection between two individuals, events, ideas, or pieces of information in a text.'},
  {code:'RI.K.4',domain:'RI',grade:0,cluster:'Craft & Structure',text:'With prompting and support, ask and answer questions about unknown words in a text.'},
  {code:'RI.K.5',domain:'RI',grade:0,cluster:'Craft & Structure',text:'Identify the front cover, back cover, and title page of a book.'},
  {code:'RI.K.6',domain:'RI',grade:0,cluster:'Craft & Structure',text:'Name the author and illustrator of a text and define the role of each in presenting ideas or information in a text.'},
  {code:'RI.K.7',domain:'RI',grade:0,cluster:'Integration',text:'With prompting and support, describe the relationship between illustrations and the text in which they appear.'},
  {code:'RI.K.8',domain:'RI',grade:0,cluster:'Integration',text:'With prompting and support, identify the reasons an author gives to support points in a text.'},
  {code:'RI.K.9',domain:'RI',grade:0,cluster:'Integration',text:'With prompting and support, identify basic similarities in and differences between two texts on the same topic.'},
  {code:'RI.K.10',domain:'RI',grade:0,cluster:'Range',text:'Actively engage in group reading activities with purpose and understanding.'},
  // RF - Foundational Skills
  {code:'RF.K.1',domain:'RF',grade:0,cluster:'Print Concepts',text:'Demonstrate understanding of the organization and basic features of print.'},
  {code:'RF.K.2',domain:'RF',grade:0,cluster:'Phonological Awareness',text:'Demonstrate understanding of spoken words, syllables, and sounds (phonemes).'},
  {code:'RF.K.3',domain:'RF',grade:0,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.K.4',domain:'RF',grade:0,cluster:'Fluency',text:'Read emergent-reader texts with purpose and understanding.'},
  // W - Writing
  {code:'W.K.1',domain:'W',grade:0,cluster:'Text Types',text:'Use a combination of drawing, dictating, and writing to compose opinion pieces.'},
  {code:'W.K.2',domain:'W',grade:0,cluster:'Text Types',text:'Use a combination of drawing, dictating, and writing to compose informative/explanatory texts.'},
  {code:'W.K.3',domain:'W',grade:0,cluster:'Text Types',text:'Use a combination of drawing, dictating, and writing to narrate a single event or several loosely linked events.'},
  {code:'W.K.5',domain:'W',grade:0,cluster:'Production',text:'With guidance and support from adults, respond to questions and suggestions from peers and add details to strengthen writing.'},
  {code:'W.K.6',domain:'W',grade:0,cluster:'Production',text:'With guidance and support from adults, explore a variety of digital tools to produce and publish writing.'},
  {code:'W.K.7',domain:'W',grade:0,cluster:'Research',text:'Participate in shared research and writing projects.'},
  {code:'W.K.8',domain:'W',grade:0,cluster:'Research',text:'With guidance and support from adults, recall information from experiences or gather information from provided sources to answer a question.'},
  // SL - Speaking & Listening
  {code:'SL.K.1',domain:'SL',grade:0,cluster:'Collaboration',text:'Participate in collaborative conversations with diverse partners about kindergarten topics and texts.'},
  {code:'SL.K.2',domain:'SL',grade:0,cluster:'Collaboration',text:'Confirm understanding of a text read aloud or information presented orally or through other media by asking and answering questions.'},
  {code:'SL.K.3',domain:'SL',grade:0,cluster:'Collaboration',text:'Ask and answer questions in order to seek help, get information, or clarify something that is not understood.'},
  {code:'SL.K.4',domain:'SL',grade:0,cluster:'Presentation',text:'Describe familiar people, places, things, and events and, with prompting and support, provide additional detail.'},
  {code:'SL.K.5',domain:'SL',grade:0,cluster:'Presentation',text:'Add drawings or other visual displays to descriptions as desired to provide additional detail.'},
  {code:'SL.K.6',domain:'SL',grade:0,cluster:'Presentation',text:'Speak audibly and express thoughts, feelings, and ideas clearly.'},
  // L - Language
  {code:'L.K.1',domain:'L',grade:0,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.K.2',domain:'L',grade:0,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.K.4',domain:'L',grade:0,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on kindergarten reading and content.'},
  {code:'L.K.5',domain:'L',grade:0,cluster:'Vocabulary',text:'With guidance and support from adults, explore word relationships and nuances in word meanings.'},
  {code:'L.K.6',domain:'L',grade:0,cluster:'Vocabulary',text:'Use words and phrases acquired through conversations, reading and being read to, and responding to texts.'},

  // ═══════════════ GRADE 1 ═══════════════
  {code:'RL.1.1',domain:'RL',grade:1,cluster:'Key Ideas & Details',text:'Ask and answer questions about key details in a text.'},
  {code:'RL.1.2',domain:'RL',grade:1,cluster:'Key Ideas & Details',text:'Retell stories, including key details, and demonstrate understanding of their central message or lesson.'},
  {code:'RL.1.3',domain:'RL',grade:1,cluster:'Key Ideas & Details',text:'Describe characters, settings, and major events in a story, using key details.'},
  {code:'RL.1.4',domain:'RL',grade:1,cluster:'Craft & Structure',text:'Identify words and phrases in stories or poems that suggest feelings or appeal to the senses.'},
  {code:'RL.1.5',domain:'RL',grade:1,cluster:'Craft & Structure',text:'Explain major differences between books that tell stories and books that give information.'},
  {code:'RL.1.6',domain:'RL',grade:1,cluster:'Craft & Structure',text:'Identify who is telling the story at various points in a text.'},
  {code:'RL.1.7',domain:'RL',grade:1,cluster:'Integration',text:'Use illustrations and details in a story to describe its characters, setting, or events.'},
  {code:'RL.1.9',domain:'RL',grade:1,cluster:'Integration',text:'Compare and contrast the adventures and experiences of characters in stories.'},
  {code:'RL.1.10',domain:'RL',grade:1,cluster:'Range',text:'With prompting and support, read prose and poetry of appropriate complexity for grade 1.'},
  {code:'RI.1.1',domain:'RI',grade:1,cluster:'Key Ideas & Details',text:'Ask and answer questions about key details in a text.'},
  {code:'RI.1.2',domain:'RI',grade:1,cluster:'Key Ideas & Details',text:'Identify the main topic and retell key details of a text.'},
  {code:'RI.1.3',domain:'RI',grade:1,cluster:'Key Ideas & Details',text:'Describe the connection between two individuals, events, ideas, or pieces of information in a text.'},
  {code:'RI.1.4',domain:'RI',grade:1,cluster:'Craft & Structure',text:'Ask and answer questions to help determine or clarify the meaning of words and phrases in a text.'},
  {code:'RI.1.5',domain:'RI',grade:1,cluster:'Craft & Structure',text:'Know and use various text features to locate key facts or information in a text.'},
  {code:'RI.1.6',domain:'RI',grade:1,cluster:'Craft & Structure',text:'Distinguish between information provided by pictures or other illustrations and information provided by the words in a text.'},
  {code:'RI.1.7',domain:'RI',grade:1,cluster:'Integration',text:'Use the illustrations and details in a text to describe its key ideas.'},
  {code:'RI.1.8',domain:'RI',grade:1,cluster:'Integration',text:'Identify the reasons an author gives to support points in a text.'},
  {code:'RI.1.9',domain:'RI',grade:1,cluster:'Integration',text:'Identify basic similarities in and differences between two texts on the same topic.'},
  {code:'RI.1.10',domain:'RI',grade:1,cluster:'Range',text:'With prompting and support, read informational texts appropriately complex for grade 1.'},
  {code:'RF.1.1',domain:'RF',grade:1,cluster:'Print Concepts',text:'Demonstrate understanding of the organization and basic features of print.'},
  {code:'RF.1.2',domain:'RF',grade:1,cluster:'Phonological Awareness',text:'Demonstrate understanding of spoken words, syllables, and sounds (phonemes).'},
  {code:'RF.1.3',domain:'RF',grade:1,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.1.4',domain:'RF',grade:1,cluster:'Fluency',text:'Read with sufficient accuracy and fluency to support comprehension.'},
  {code:'W.1.1',domain:'W',grade:1,cluster:'Text Types',text:'Write opinion pieces in which they introduce the topic, state an opinion, supply a reason, and provide some sense of closure.'},
  {code:'W.1.2',domain:'W',grade:1,cluster:'Text Types',text:'Write informative/explanatory texts in which they name a topic, supply some facts, and provide some sense of closure.'},
  {code:'W.1.3',domain:'W',grade:1,cluster:'Text Types',text:'Write narratives in which they recount two or more appropriately sequenced events, include details, use temporal words, and provide closure.'},
  {code:'W.1.5',domain:'W',grade:1,cluster:'Production',text:'With guidance and support from adults, focus on a topic, respond to questions and suggestions from peers, and add details to strengthen writing.'},
  {code:'W.1.6',domain:'W',grade:1,cluster:'Production',text:'With guidance and support from adults, use a variety of digital tools to produce and publish writing.'},
  {code:'W.1.7',domain:'W',grade:1,cluster:'Research',text:'Participate in shared research and writing projects.'},
  {code:'W.1.8',domain:'W',grade:1,cluster:'Research',text:'With guidance and support from adults, recall information from experiences or gather information from provided sources to answer a question.'},
  {code:'SL.1.1',domain:'SL',grade:1,cluster:'Collaboration',text:'Participate in collaborative conversations with diverse partners about grade 1 topics and texts.'},
  {code:'SL.1.2',domain:'SL',grade:1,cluster:'Collaboration',text:'Ask and answer questions about key details in a text read aloud or information presented orally or through other media.'},
  {code:'SL.1.3',domain:'SL',grade:1,cluster:'Collaboration',text:'Ask and answer questions about what a speaker says in order to gather additional information or clarify something.'},
  {code:'SL.1.4',domain:'SL',grade:1,cluster:'Presentation',text:'Describe people, places, things, and events with relevant details, expressing ideas and feelings clearly.'},
  {code:'SL.1.5',domain:'SL',grade:1,cluster:'Presentation',text:'Add drawings or other visual displays to descriptions when appropriate to clarify ideas, thoughts, and feelings.'},
  {code:'SL.1.6',domain:'SL',grade:1,cluster:'Presentation',text:'Produce complete sentences when appropriate to task and situation.'},
  {code:'L.1.1',domain:'L',grade:1,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.1.2',domain:'L',grade:1,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.1.4',domain:'L',grade:1,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 1 reading and content.'},
  {code:'L.1.5',domain:'L',grade:1,cluster:'Vocabulary',text:'With guidance and support from adults, demonstrate understanding of word relationships and nuances in word meanings.'},
  {code:'L.1.6',domain:'L',grade:1,cluster:'Vocabulary',text:'Use words and phrases acquired through conversations, reading and being read to, and responding to texts.'},

  // ═══════════════ GRADE 2 ═══════════════
  {code:'RL.2.1',domain:'RL',grade:2,cluster:'Key Ideas & Details',text:'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.'},
  {code:'RL.2.2',domain:'RL',grade:2,cluster:'Key Ideas & Details',text:'Recount stories, including fables and folktales from diverse cultures, and determine their central message, lesson, or moral.'},
  {code:'RL.2.3',domain:'RL',grade:2,cluster:'Key Ideas & Details',text:'Describe how characters in a story respond to major events and challenges.'},
  {code:'RL.2.4',domain:'RL',grade:2,cluster:'Craft & Structure',text:'Describe how words and phrases supply rhythm and meaning in a story, poem, or song.'},
  {code:'RL.2.5',domain:'RL',grade:2,cluster:'Craft & Structure',text:'Describe the overall structure of a story, including how the beginning introduces the story and the ending concludes the action.'},
  {code:'RL.2.6',domain:'RL',grade:2,cluster:'Craft & Structure',text:'Acknowledge differences in the points of view of characters, including by speaking in a different voice for each character when reading dialogue aloud.'},
  {code:'RL.2.7',domain:'RL',grade:2,cluster:'Integration',text:'Use information from illustrations and words in a print or digital text to demonstrate understanding of characters, setting, or plot.'},
  {code:'RL.2.9',domain:'RL',grade:2,cluster:'Integration',text:'Compare and contrast two or more versions of the same story by different authors or from different cultures.'},
  {code:'RL.2.10',domain:'RL',grade:2,cluster:'Range',text:'By the end of the year, read and comprehend literature in the grades 2-3 text complexity band proficiently.'},
  {code:'RI.2.1',domain:'RI',grade:2,cluster:'Key Ideas & Details',text:'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.'},
  {code:'RI.2.2',domain:'RI',grade:2,cluster:'Key Ideas & Details',text:'Identify the main topic of a multi-paragraph text as well as the focus of specific paragraphs within the text.'},
  {code:'RI.2.3',domain:'RI',grade:2,cluster:'Key Ideas & Details',text:'Describe the connection between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text.'},
  {code:'RI.2.4',domain:'RI',grade:2,cluster:'Craft & Structure',text:'Determine the meaning of words and phrases in a text relevant to a grade 2 topic or subject area.'},
  {code:'RI.2.5',domain:'RI',grade:2,cluster:'Craft & Structure',text:'Know and use various text features to locate key facts or information in a text efficiently.'},
  {code:'RI.2.6',domain:'RI',grade:2,cluster:'Craft & Structure',text:'Identify the main purpose of a text, including what the author wants to answer, explain, or describe.'},
  {code:'RI.2.7',domain:'RI',grade:2,cluster:'Integration',text:'Explain how specific images contribute to and clarify a text.'},
  {code:'RI.2.8',domain:'RI',grade:2,cluster:'Integration',text:'Describe how reasons support specific points the author makes in a text.'},
  {code:'RI.2.9',domain:'RI',grade:2,cluster:'Integration',text:'Compare and contrast the most important points presented by two texts on the same topic.'},
  {code:'RI.2.10',domain:'RI',grade:2,cluster:'Range',text:'By the end of year, read and comprehend informational texts in the grades 2-3 text complexity band proficiently.'},
  {code:'RF.2.3',domain:'RF',grade:2,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.2.4',domain:'RF',grade:2,cluster:'Fluency',text:'Read with sufficient accuracy and fluency to support comprehension.'},
  {code:'W.2.1',domain:'W',grade:2,cluster:'Text Types',text:'Write opinion pieces introducing the topic, stating an opinion, supplying reasons with linking words, and providing closure.'},
  {code:'W.2.2',domain:'W',grade:2,cluster:'Text Types',text:'Write informative/explanatory texts introducing a topic, using facts and definitions, and providing closure.'},
  {code:'W.2.3',domain:'W',grade:2,cluster:'Text Types',text:'Write narratives recounting well-elaborated events with details, temporal words, and closure.'},
  {code:'W.2.5',domain:'W',grade:2,cluster:'Production',text:'With guidance and support from adults and peers, focus on a topic and strengthen writing by revising and editing.'},
  {code:'W.2.6',domain:'W',grade:2,cluster:'Production',text:'With guidance and support from adults, use a variety of digital tools to produce and publish writing.'},
  {code:'W.2.7',domain:'W',grade:2,cluster:'Research',text:'Participate in shared research and writing projects.'},
  {code:'W.2.8',domain:'W',grade:2,cluster:'Research',text:'Recall information from experiences or gather information from provided sources to answer a question.'},
  {code:'SL.2.1',domain:'SL',grade:2,cluster:'Collaboration',text:'Participate in collaborative conversations with diverse partners about grade 2 topics and texts.'},
  {code:'SL.2.2',domain:'SL',grade:2,cluster:'Collaboration',text:'Recount or describe key ideas or details from a text read aloud or information presented orally or through other media.'},
  {code:'SL.2.3',domain:'SL',grade:2,cluster:'Collaboration',text:'Ask and answer questions about what a speaker says in order to clarify comprehension, gather additional information, or deepen understanding.'},
  {code:'SL.2.4',domain:'SL',grade:2,cluster:'Presentation',text:'Tell a story or recount an experience with appropriate facts and relevant, descriptive details, speaking audibly in coherent sentences.'},
  {code:'SL.2.5',domain:'SL',grade:2,cluster:'Presentation',text:'Create audio recordings of stories or poems; add drawings or other visual displays to stories or recounts of experiences.'},
  {code:'SL.2.6',domain:'SL',grade:2,cluster:'Presentation',text:'Produce complete sentences when appropriate to task and situation in order to provide requested detail or clarification.'},
  {code:'L.2.1',domain:'L',grade:2,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.2.2',domain:'L',grade:2,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.2.3',domain:'L',grade:2,cluster:'Knowledge of Language',text:'Use knowledge of language and its conventions when writing, speaking, reading, or listening.'},
  {code:'L.2.4',domain:'L',grade:2,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 2 reading and content.'},
  {code:'L.2.5',domain:'L',grade:2,cluster:'Vocabulary',text:'Demonstrate understanding of word relationships and nuances in word meanings.'},
  {code:'L.2.6',domain:'L',grade:2,cluster:'Vocabulary',text:'Use words and phrases acquired through conversations, reading and being read to, and responding to texts.'},

  // ═══════════════ GRADE 3 ═══════════════
  {code:'RL.3.1',domain:'RL',grade:3,cluster:'Key Ideas & Details',text:'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.'},
  {code:'RL.3.2',domain:'RL',grade:3,cluster:'Key Ideas & Details',text:'Recount stories including fables, folktales, and myths; determine the central message, lesson, or moral.'},
  {code:'RL.3.3',domain:'RL',grade:3,cluster:'Key Ideas & Details',text:'Describe characters in a story (traits, motivations, feelings) and explain how their actions contribute to the sequence of events.'},
  {code:'RL.3.4',domain:'RL',grade:3,cluster:'Craft & Structure',text:'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language.'},
  {code:'RL.3.5',domain:'RL',grade:3,cluster:'Craft & Structure',text:'Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza.'},
  {code:'RL.3.6',domain:'RL',grade:3,cluster:'Craft & Structure',text:'Distinguish their own point of view from that of the narrator or those of the characters.'},
  {code:'RL.3.7',domain:'RL',grade:3,cluster:'Integration',text:'Explain how specific aspects of a text\'s illustrations contribute to what is conveyed by the words in a story.'},
  {code:'RL.3.9',domain:'RL',grade:3,cluster:'Integration',text:'Compare and contrast the themes, settings, and plots of stories written by the same author about the same or similar characters.'},
  {code:'RL.3.10',domain:'RL',grade:3,cluster:'Range',text:'By the end of the year, read and comprehend literature at the high end of the grades 2-3 text complexity band independently and proficiently.'},
  {code:'RI.3.1',domain:'RI',grade:3,cluster:'Key Ideas & Details',text:'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.'},
  {code:'RI.3.2',domain:'RI',grade:3,cluster:'Key Ideas & Details',text:'Determine the main idea of a text; recount the key details and explain how they support the main idea.'},
  {code:'RI.3.3',domain:'RI',grade:3,cluster:'Key Ideas & Details',text:'Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures, using language that pertains to time, sequence, and cause/effect.'},
  {code:'RI.3.4',domain:'RI',grade:3,cluster:'Craft & Structure',text:'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 3 topic or subject area.'},
  {code:'RI.3.5',domain:'RI',grade:3,cluster:'Craft & Structure',text:'Use text features and search tools to locate information relevant to a given topic efficiently.'},
  {code:'RI.3.6',domain:'RI',grade:3,cluster:'Craft & Structure',text:'Distinguish their own point of view from that of the author of a text.'},
  {code:'RI.3.7',domain:'RI',grade:3,cluster:'Integration',text:'Use information gained from illustrations and the words in a text to demonstrate understanding of the text.'},
  {code:'RI.3.8',domain:'RI',grade:3,cluster:'Integration',text:'Describe the logical connection between particular sentences and paragraphs in a text.'},
  {code:'RI.3.9',domain:'RI',grade:3,cluster:'Integration',text:'Compare and contrast the most important points and key details presented in two texts on the same topic.'},
  {code:'RI.3.10',domain:'RI',grade:3,cluster:'Range',text:'By the end of the year, read and comprehend informational texts at the high end of the grades 2-3 text complexity band independently and proficiently.'},
  {code:'RF.3.3',domain:'RF',grade:3,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.3.4',domain:'RF',grade:3,cluster:'Fluency',text:'Read with sufficient accuracy and fluency to support comprehension.'},
  {code:'W.3.1',domain:'W',grade:3,cluster:'Text Types',text:'Write opinion pieces on topics or texts, supporting a point of view with reasons.'},
  {code:'W.3.2',domain:'W',grade:3,cluster:'Text Types',text:'Write informative/explanatory texts to examine a topic and convey ideas and information clearly.'},
  {code:'W.3.3',domain:'W',grade:3,cluster:'Text Types',text:'Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.'},
  {code:'W.3.4',domain:'W',grade:3,cluster:'Production',text:'With guidance and support from adults, produce writing in which the development and organization are appropriate to task and purpose.'},
  {code:'W.3.5',domain:'W',grade:3,cluster:'Production',text:'With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, and editing.'},
  {code:'W.3.6',domain:'W',grade:3,cluster:'Production',text:'With guidance and support from adults, use technology to produce and publish writing.'},
  {code:'W.3.7',domain:'W',grade:3,cluster:'Research',text:'Conduct short research projects that build knowledge about a topic.'},
  {code:'W.3.8',domain:'W',grade:3,cluster:'Research',text:'Recall information from experiences or gather information from print and digital sources; take brief notes on sources and sort evidence into provided categories.'},
  {code:'W.3.10',domain:'W',grade:3,cluster:'Range',text:'Write routinely over extended time frames and shorter time frames for a range of discipline-specific tasks, purposes, and audiences.'},
  {code:'SL.3.1',domain:'SL',grade:3,cluster:'Collaboration',text:'Engage effectively in a range of collaborative discussions, building on others\' ideas and expressing their own clearly.'},
  {code:'SL.3.2',domain:'SL',grade:3,cluster:'Collaboration',text:'Determine the main ideas and supporting details of a text read aloud or information presented in diverse media and formats.'},
  {code:'SL.3.3',domain:'SL',grade:3,cluster:'Collaboration',text:'Ask and answer questions about information from a speaker, offering appropriate elaboration and detail.'},
  {code:'SL.3.4',domain:'SL',grade:3,cluster:'Presentation',text:'Report on a topic or text, tell a story, or recount an experience with appropriate facts and relevant, descriptive details, speaking clearly.'},
  {code:'SL.3.5',domain:'SL',grade:3,cluster:'Presentation',text:'Create engaging audio recordings of stories or poems that demonstrate fluid reading at an understandable pace.'},
  {code:'SL.3.6',domain:'SL',grade:3,cluster:'Presentation',text:'Speak in complete sentences when appropriate to task and situation.'},
  {code:'L.3.1',domain:'L',grade:3,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.3.2',domain:'L',grade:3,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.3.3',domain:'L',grade:3,cluster:'Knowledge of Language',text:'Use knowledge of language and its conventions when writing, speaking, reading, or listening.'},
  {code:'L.3.4',domain:'L',grade:3,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning word and phrases based on grade 3 reading and content.'},
  {code:'L.3.5',domain:'L',grade:3,cluster:'Vocabulary',text:'Demonstrate understanding of figurative language, word relationships and nuances in word meanings.'},
  {code:'L.3.6',domain:'L',grade:3,cluster:'Vocabulary',text:'Acquire and use accurately grade-appropriate conversational, general academic, and domain-specific words and phrases.'},

  // ═══════════════ GRADE 4 ═══════════════
  {code:'RL.4.1',domain:'RL',grade:4,cluster:'Key Ideas & Details',text:'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.'},
  {code:'RL.4.2',domain:'RL',grade:4,cluster:'Key Ideas & Details',text:'Determine a theme of a story, drama, or poem from details in the text; summarize the text.'},
  {code:'RL.4.3',domain:'RL',grade:4,cluster:'Key Ideas & Details',text:'Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text.'},
  {code:'RL.4.4',domain:'RL',grade:4,cluster:'Craft & Structure',text:'Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology.'},
  {code:'RL.4.5',domain:'RL',grade:4,cluster:'Craft & Structure',text:'Explain major differences between poems, drama, and prose, and refer to the structural elements of poems and drama.'},
  {code:'RL.4.6',domain:'RL',grade:4,cluster:'Craft & Structure',text:'Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations.'},
  {code:'RL.4.7',domain:'RL',grade:4,cluster:'Integration',text:'Make connections between the text of a story or drama and a visual or oral presentation of the text.'},
  {code:'RL.4.9',domain:'RL',grade:4,cluster:'Integration',text:'Compare and contrast the treatment of similar themes and topics and patterns of events in stories, myths, and traditional literature from different cultures.'},
  {code:'RL.4.10',domain:'RL',grade:4,cluster:'Range',text:'By the end of the year, read and comprehend literature in the grades 4-5 text complexity band proficiently.'},
  {code:'RI.4.1',domain:'RI',grade:4,cluster:'Key Ideas & Details',text:'Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.'},
  {code:'RI.4.2',domain:'RI',grade:4,cluster:'Key Ideas & Details',text:'Determine the main idea of a text and explain how it is supported by key details; summarize the text.'},
  {code:'RI.4.3',domain:'RI',grade:4,cluster:'Key Ideas & Details',text:'Explain events, procedures, ideas, or concepts in a historical, scientific, or technical text, including what happened and why.'},
  {code:'RI.4.4',domain:'RI',grade:4,cluster:'Craft & Structure',text:'Determine the meaning of general academic and domain-specific words or phrases in a text relevant to a grade 4 topic or subject area.'},
  {code:'RI.4.5',domain:'RI',grade:4,cluster:'Craft & Structure',text:'Describe the overall structure of events, ideas, concepts, or information in a text or part of a text.'},
  {code:'RI.4.6',domain:'RI',grade:4,cluster:'Craft & Structure',text:'Compare and contrast a firsthand and secondhand account of the same event or topic; describe the differences in focus and the information provided.'},
  {code:'RI.4.7',domain:'RI',grade:4,cluster:'Integration',text:'Interpret information presented visually, orally, or quantitatively and explain how the information contributes to an understanding of the text.'},
  {code:'RI.4.8',domain:'RI',grade:4,cluster:'Integration',text:'Explain how an author uses reasons and evidence to support particular points in a text.'},
  {code:'RI.4.9',domain:'RI',grade:4,cluster:'Integration',text:'Integrate information from two texts on the same topic in order to write or speak about the subject knowledgeably.'},
  {code:'RI.4.10',domain:'RI',grade:4,cluster:'Range',text:'By the end of year, read and comprehend informational texts in the grades 4-5 text complexity band proficiently.'},
  {code:'RF.4.3',domain:'RF',grade:4,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.4.4',domain:'RF',grade:4,cluster:'Fluency',text:'Read with sufficient accuracy and fluency to support comprehension.'},
  {code:'W.4.1',domain:'W',grade:4,cluster:'Text Types',text:'Write opinion pieces on topics or texts, supporting a point of view with reasons and information.'},
  {code:'W.4.2',domain:'W',grade:4,cluster:'Text Types',text:'Write informative/explanatory texts to examine a topic and convey ideas and information clearly.'},
  {code:'W.4.3',domain:'W',grade:4,cluster:'Text Types',text:'Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.'},
  {code:'W.4.4',domain:'W',grade:4,cluster:'Production',text:'Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.'},
  {code:'W.4.5',domain:'W',grade:4,cluster:'Production',text:'With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, and editing.'},
  {code:'W.4.6',domain:'W',grade:4,cluster:'Production',text:'With some guidance and support from adults, use technology to produce and publish writing as well as to interact and collaborate with others.'},
  {code:'W.4.7',domain:'W',grade:4,cluster:'Research',text:'Conduct short research projects that build knowledge through investigation of different aspects of a topic.'},
  {code:'W.4.8',domain:'W',grade:4,cluster:'Research',text:'Recall relevant information from experiences or gather relevant information from print and digital sources; take notes and categorize information.'},
  {code:'W.4.9',domain:'W',grade:4,cluster:'Research',text:'Draw evidence from literary or informational texts to support analysis, reflection, and research.'},
  {code:'W.4.10',domain:'W',grade:4,cluster:'Range',text:'Write routinely over extended time frames and shorter time frames for a range of discipline-specific tasks, purposes, and audiences.'},
  {code:'SL.4.1',domain:'SL',grade:4,cluster:'Collaboration',text:'Engage effectively in a range of collaborative discussions, building on others\' ideas and expressing their own clearly.'},
  {code:'SL.4.2',domain:'SL',grade:4,cluster:'Collaboration',text:'Paraphrase portions of a text read aloud or information presented in diverse media and formats.'},
  {code:'SL.4.3',domain:'SL',grade:4,cluster:'Collaboration',text:'Identify the reasons and evidence a speaker provides to support particular points.'},
  {code:'SL.4.4',domain:'SL',grade:4,cluster:'Presentation',text:'Report on a topic or text, tell a story, or recount an experience in an organized manner, using appropriate facts and relevant details to support main ideas.'},
  {code:'SL.4.5',domain:'SL',grade:4,cluster:'Presentation',text:'Add audio recordings and visual displays to presentations when appropriate to enhance the development of main ideas or themes.'},
  {code:'SL.4.6',domain:'SL',grade:4,cluster:'Presentation',text:'Differentiate between contexts that call for formal English and situations where informal discourse is appropriate.'},
  {code:'L.4.1',domain:'L',grade:4,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.4.2',domain:'L',grade:4,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.4.3',domain:'L',grade:4,cluster:'Knowledge of Language',text:'Use knowledge of language and its conventions when writing, speaking, reading, or listening.'},
  {code:'L.4.4',domain:'L',grade:4,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 4 reading and content.'},
  {code:'L.4.5',domain:'L',grade:4,cluster:'Vocabulary',text:'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'},
  {code:'L.4.6',domain:'L',grade:4,cluster:'Vocabulary',text:'Acquire and use accurately grade-appropriate general academic and domain-specific words and phrases.'},

  // ═══════════════ GRADE 5 ═══════════════
  {code:'RL.5.1',domain:'RL',grade:5,cluster:'Key Ideas & Details',text:'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.'},
  {code:'RL.5.2',domain:'RL',grade:5,cluster:'Key Ideas & Details',text:'Determine a theme from details in the text, including how characters respond to challenges or how the speaker in a poem reflects upon a topic; summarize.'},
  {code:'RL.5.3',domain:'RL',grade:5,cluster:'Key Ideas & Details',text:'Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text.'},
  {code:'RL.5.4',domain:'RL',grade:5,cluster:'Craft & Structure',text:'Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.'},
  {code:'RL.5.5',domain:'RL',grade:5,cluster:'Craft & Structure',text:'Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.'},
  {code:'RL.5.6',domain:'RL',grade:5,cluster:'Craft & Structure',text:'Describe how a narrator\'s or speaker\'s point of view influences how events are described.'},
  {code:'RL.5.7',domain:'RL',grade:5,cluster:'Integration',text:'Analyze how visual and multimedia elements contribute to the meaning, tone, or beauty of a text.'},
  {code:'RL.5.9',domain:'RL',grade:5,cluster:'Integration',text:'Compare and contrast stories in the same genre on their approaches to similar themes and topics.'},
  {code:'RL.5.10',domain:'RL',grade:5,cluster:'Range',text:'By the end of the year, read and comprehend literature at the high end of the grades 4-5 text complexity band independently and proficiently.'},
  {code:'RI.5.1',domain:'RI',grade:5,cluster:'Key Ideas & Details',text:'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.'},
  {code:'RI.5.2',domain:'RI',grade:5,cluster:'Key Ideas & Details',text:'Determine two or more main ideas of a text and explain how they are supported by key details; summarize the text.'},
  {code:'RI.5.3',domain:'RI',grade:5,cluster:'Key Ideas & Details',text:'Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a historical, scientific, or technical text.'},
  {code:'RI.5.4',domain:'RI',grade:5,cluster:'Craft & Structure',text:'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 5 topic or subject area.'},
  {code:'RI.5.5',domain:'RI',grade:5,cluster:'Craft & Structure',text:'Compare and contrast the overall structure of events, ideas, concepts, or information in two or more texts.'},
  {code:'RI.5.6',domain:'RI',grade:5,cluster:'Craft & Structure',text:'Analyze multiple accounts of the same event or topic, noting important similarities and differences in the point of view they represent.'},
  {code:'RI.5.7',domain:'RI',grade:5,cluster:'Integration',text:'Draw on information from multiple print or digital sources, demonstrating the ability to locate an answer to a question quickly or to solve a problem efficiently.'},
  {code:'RI.5.8',domain:'RI',grade:5,cluster:'Integration',text:'Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point(s).'},
  {code:'RI.5.9',domain:'RI',grade:5,cluster:'Integration',text:'Integrate information from several texts on the same topic in order to write or speak about the subject knowledgeably.'},
  {code:'RI.5.10',domain:'RI',grade:5,cluster:'Range',text:'By the end of the year, read and comprehend informational texts at the high end of the grades 4-5 text complexity band independently and proficiently.'},
  {code:'RF.5.3',domain:'RF',grade:5,cluster:'Phonics',text:'Know and apply grade-level phonics and word analysis skills in decoding words.'},
  {code:'RF.5.4',domain:'RF',grade:5,cluster:'Fluency',text:'Read with sufficient accuracy and fluency to support comprehension.'},
  {code:'W.5.1',domain:'W',grade:5,cluster:'Text Types',text:'Write opinion pieces on topics or texts, supporting a point of view with reasons and information.'},
  {code:'W.5.2',domain:'W',grade:5,cluster:'Text Types',text:'Write informative/explanatory texts to examine a topic and convey ideas and information clearly.'},
  {code:'W.5.3',domain:'W',grade:5,cluster:'Text Types',text:'Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.'},
  {code:'W.5.4',domain:'W',grade:5,cluster:'Production',text:'Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.'},
  {code:'W.5.5',domain:'W',grade:5,cluster:'Production',text:'With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.'},
  {code:'W.5.6',domain:'W',grade:5,cluster:'Production',text:'With some guidance and support from adults, use technology to produce and publish writing as well as to interact and collaborate with others.'},
  {code:'W.5.7',domain:'W',grade:5,cluster:'Research',text:'Conduct short research projects that use several sources to build knowledge through investigation of different aspects of a topic.'},
  {code:'W.5.8',domain:'W',grade:5,cluster:'Research',text:'Recall relevant information from experiences or gather relevant information from print and digital sources; summarize or paraphrase information.'},
  {code:'W.5.9',domain:'W',grade:5,cluster:'Research',text:'Draw evidence from literary or informational texts to support analysis, reflection, and research.'},
  {code:'W.5.10',domain:'W',grade:5,cluster:'Range',text:'Write routinely over extended time frames and shorter time frames for a range of discipline-specific tasks, purposes, and audiences.'},
  {code:'SL.5.1',domain:'SL',grade:5,cluster:'Collaboration',text:'Engage effectively in a range of collaborative discussions, building on others\' ideas and expressing their own clearly.'},
  {code:'SL.5.2',domain:'SL',grade:5,cluster:'Collaboration',text:'Summarize a written text read aloud or information presented in diverse media and formats.'},
  {code:'SL.5.3',domain:'SL',grade:5,cluster:'Collaboration',text:'Summarize the points a speaker makes and explain how each claim is supported by reasons and evidence.'},
  {code:'SL.5.4',domain:'SL',grade:5,cluster:'Presentation',text:'Report on a topic or text or present an opinion, sequencing ideas logically and using appropriate facts and relevant details to support main ideas.'},
  {code:'SL.5.5',domain:'SL',grade:5,cluster:'Presentation',text:'Include multimedia components and visual displays in presentations when appropriate to enhance the development of main ideas or themes.'},
  {code:'SL.5.6',domain:'SL',grade:5,cluster:'Presentation',text:'Adapt speech to a variety of contexts and tasks, using formal English when appropriate to task and situation.'},
  {code:'L.5.1',domain:'L',grade:5,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.'},
  {code:'L.5.2',domain:'L',grade:5,cluster:'Conventions',text:'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.'},
  {code:'L.5.3',domain:'L',grade:5,cluster:'Knowledge of Language',text:'Use knowledge of language and its conventions when writing, speaking, reading, or listening.'},
  {code:'L.5.4',domain:'L',grade:5,cluster:'Vocabulary',text:'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 5 reading and content.'},
  {code:'L.5.5',domain:'L',grade:5,cluster:'Vocabulary',text:'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'},
  {code:'L.5.6',domain:'L',grade:5,cluster:'Vocabulary',text:'Acquire and use accurately grade-appropriate general academic and domain-specific words and phrases.'},
]
