// Scoring Rubrics extracted from CCSS-Aligned Writing Rubrics K-3 + Reading Response Pack
// 4-column scale: 1=Needs Guidance/Emerging, 2=Developing, 3=Meets Standards, 4=Exceeds Standards

export interface ScoringRubric {
  name: string
  domain: 'writing' | 'reading' | 'speaking'
  grades: number[] // which grades this rubric applies to (0=K, 1-5)
  criteria: { label: string; standard?: string }[]
}

export const SCORING_RUBRICS: ScoringRubric[] = [
  // ─── WRITING: OPINION ────────────────────────────────────────────
  { name: 'Opinion Writing', domain: 'writing', grades: [0],
    criteria: [
      { label: 'I tell my opinion', standard: 'K.W.1' },
      { label: 'I give a reason for my opinion using "because"', standard: 'K.W.1' },
      { label: 'I stay focused on one topic', standard: 'K.W.5' },
      { label: 'My picture matches my words', standard: 'K.W.1' },
      { label: 'I write in a complete sentence' },
      { label: 'I use a capital letter to begin sentences and for "I"', standard: 'K.L.2a' },
      { label: 'I use ending punctuation', standard: 'K.L.2b' },
      { label: 'I can spell words phonetically', standard: 'K.L.2d' },
      { label: 'I have spaces between my words', standard: 'K.RF.1c' },
    ] },
  { name: 'Opinion Writing', domain: 'writing', grades: [1],
    criteria: [
      { label: 'I stated my opinion', standard: 'W.1.1' },
      { label: 'I gave reasons that support my opinion', standard: 'W.1.1' },
      { label: 'I stayed on topic throughout' },
      { label: 'I wrote an opening to get my reader\'s attention' },
      { label: 'I wrote an ending for my piece', standard: 'W.1.1' },
      { label: 'I added details', standard: 'W.1.5' },
      { label: 'I wrote in complete sentences', standard: 'L.1.1' },
      { label: 'I used capital letters and ending punctuation', standard: 'L.1.2' },
      { label: 'I used spelling patterns to spell words correctly', standard: 'L.1.2d' },
    ] },
  { name: 'Opinion Writing', domain: 'writing', grades: [2],
    criteria: [
      { label: 'I stated my opinion and stayed on topic', standard: 'W.2.1' },
      { label: 'I gave reasons that support my opinion', standard: 'W.2.1' },
      { label: 'I added details', standard: 'W.2.5' },
      { label: 'I wrote an opening to get my reader\'s attention' },
      { label: 'I wrote a concluding statement', standard: 'W.2.1' },
      { label: 'I used linking words (because, and, also)', standard: 'W.2.1' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.2.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.2.2' },
      { label: 'I used spelling patterns to spell words', standard: 'L.2.2d' },
    ] },
  { name: 'Opinion Writing', domain: 'writing', grades: [3],
    criteria: [
      { label: 'I clearly stated my opinion and stayed on topic', standard: 'W.3.1' },
      { label: 'I gave specific reasons that support my opinion', standard: 'W.3.1b' },
      { label: 'I elaborated on my reasons with additional details', standard: 'W.3.1b' },
      { label: 'I wrote an opening that introduced the topic and stated my opinion', standard: 'W.3.1a' },
      { label: 'I used linking words and phrases', standard: 'W.3.1c' },
      { label: 'I wrote a conclusion for my piece', standard: 'W.3.1d' },
      { label: 'I set up an organizational structure in my writing' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.3.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.3.2' },
    ] },
  { name: 'Opinion Writing', domain: 'writing', grades: [4, 5],
    criteria: [
      { label: 'Clear opinion stated with focused topic' },
      { label: 'Specific reasons supported with facts and details' },
      { label: 'Engaging introduction that establishes position' },
      { label: 'Logical organizational structure with paragraphs' },
      { label: 'Effective use of linking words and transitions' },
      { label: 'Strong concluding statement' },
      { label: 'Varied sentence structure and word choice' },
      { label: 'Correct grammar, capitalization, punctuation' },
      { label: 'Accurate spelling using known patterns' },
    ] },

  // ─── WRITING: NARRATIVE ──────────────────────────────────────────
  { name: 'Narrative Writing', domain: 'writing', grades: [0],
    criteria: [
      { label: 'I wrote about something that happened', standard: 'K.W.3' },
      { label: 'I told who was there and what I did' },
      { label: 'I added how I felt', standard: 'K.W.3' },
      { label: 'My picture matches my words' },
      { label: 'I write in a complete sentence' },
      { label: 'I use a capital letter correctly', standard: 'K.L.2a' },
      { label: 'I use ending punctuation', standard: 'K.L.2b' },
      { label: 'I can spell words phonetically', standard: 'K.L.2d' },
    ] },
  { name: 'Narrative Writing', domain: 'writing', grades: [1],
    criteria: [
      { label: 'I wrote a story with at least two events', standard: 'W.1.3' },
      { label: 'I added interesting details to my story', standard: 'W.1.3' },
      { label: 'I had a clear ending to my story', standard: 'W.1.3' },
      { label: 'I used temporal words to show order', standard: 'W.1.3' },
      { label: 'I used adjectives to describe', standard: 'L.1.1f' },
      { label: 'I wrote in complete sentences with subject-verb agreement', standard: 'L.1.1c' },
      { label: 'I used capital letters and punctuation', standard: 'L.1.2' },
      { label: 'I used spelling patterns to spell words', standard: 'L.1.2d' },
    ] },
  { name: 'Narrative Writing', domain: 'writing', grades: [2],
    criteria: [
      { label: 'I wrote about one time I did something', standard: 'W.2.3' },
      { label: 'I added interesting details to my story', standard: 'W.2.3' },
      { label: 'I included thoughts, actions, and feelings', standard: 'W.2.3' },
      { label: 'I wrote a strong opening that establishes the situation', standard: 'W.2.3' },
      { label: 'I wrote a good ending', standard: 'W.2.3' },
      { label: 'I used transition words', standard: 'W.2.3' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.2.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.2.2' },
      { label: 'I used spelling patterns to spell words', standard: 'L.2.2d' },
    ] },
  { name: 'Narrative Writing', domain: 'writing', grades: [3],
    criteria: [
      { label: 'I wrote about one experience and stayed on topic', standard: 'W.3.3' },
      { label: 'I added details with descriptions of actions', standard: 'W.3.3a' },
      { label: 'I developed events with dialogue, thoughts, and feelings', standard: 'W.3.3b' },
      { label: 'I wrote a strong opening establishing situation and characters', standard: 'W.3.3a' },
      { label: 'I wrote an ending that gives closure', standard: 'W.3.3d' },
      { label: 'I used temporal words to show event order', standard: 'W.3.3c' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.3.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.3.2' },
      { label: 'I used spelling patterns to spell words', standard: 'L.3.2' },
    ] },
  { name: 'Narrative Writing', domain: 'writing', grades: [4, 5],
    criteria: [
      { label: 'Focused narrative with clear sequence of events' },
      { label: 'Vivid details with descriptions and sensory details' },
      { label: 'Developed characters with dialogue, thoughts, and feelings' },
      { label: 'Engaging opening that establishes situation' },
      { label: 'Satisfying conclusion with sense of closure' },
      { label: 'Effective use of transitions and pacing' },
      { label: 'Varied sentence structure and precise word choice' },
      { label: 'Correct grammar, capitalization, punctuation' },
      { label: 'Accurate spelling' },
    ] },

  // ─── WRITING: INFORMATIVE ────────────────────────────────────────
  { name: 'Informational Writing', domain: 'writing', grades: [0],
    criteria: [
      { label: 'I told my reader what I was writing about', standard: 'K.W.2' },
      { label: 'I wrote what I knew about the topic', standard: 'K.W.2' },
      { label: 'I added pictures to go with my writing' },
      { label: 'I write in a complete sentence' },
      { label: 'I use a capital letter correctly', standard: 'K.L.2a' },
      { label: 'I use ending punctuation', standard: 'K.L.2b' },
      { label: 'I can spell words phonetically', standard: 'K.L.2d' },
    ] },
  { name: 'Informational Writing', domain: 'writing', grades: [1],
    criteria: [
      { label: 'I told my reader what I was writing about', standard: 'W.1.2' },
      { label: 'I included facts about my topic', standard: 'W.1.2' },
      { label: 'I provided a sense of closure' },
      { label: 'I wrote in complete sentences with subject-verb agreement', standard: 'L.1.1c' },
      { label: 'I used capital letters and punctuation', standard: 'L.1.2' },
      { label: 'I used spelling patterns and high-frequency words', standard: 'L.1.2d' },
    ] },
  { name: 'Informational Writing', domain: 'writing', grades: [2],
    criteria: [
      { label: 'I stayed on topic, picking facts relevant to topic', standard: 'W.2.2' },
      { label: 'I included facts to develop my point', standard: 'W.2.2' },
      { label: 'I included definitions when applicable', standard: 'W.2.2' },
      { label: 'I wrote an opening that introduced my topic', standard: 'W.2.2' },
      { label: 'I provided an ending statement or section', standard: 'W.2.2' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.2.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.2.2' },
      { label: 'I used spelling patterns to spell words', standard: 'L.2.2d' },
    ] },
  { name: 'Informational Writing', domain: 'writing', grades: [3],
    criteria: [
      { label: 'I stayed focused on topic and showed understanding', standard: 'W.3.2a' },
      { label: 'I included details, facts, and definitions to develop topic', standard: 'W.3.2b' },
      { label: 'I used digital and print sources to gather information', standard: 'W.3.8' },
      { label: 'I used notes from sources to share in my own words', standard: 'W.3.8' },
      { label: 'I wrote an opening that introduced the topic', standard: 'W.3.2a' },
      { label: 'I used linking words and phrases', standard: 'W.3.2c' },
      { label: 'I wrote a conclusion for my piece', standard: 'W.3.2d' },
      { label: 'I wrote in complete sentences with correct grammar', standard: 'L.3.1' },
      { label: 'I used correct capitalization and punctuation', standard: 'L.3.2' },
    ] },
  { name: 'Informational Writing', domain: 'writing', grades: [4, 5],
    criteria: [
      { label: 'Focused topic with clear understanding demonstrated' },
      { label: 'Rich facts, details, and definitions to develop topic' },
      { label: 'Information from multiple sources in own words' },
      { label: 'Engaging introduction that establishes topic' },
      { label: 'Logical grouping of related information' },
      { label: 'Effective use of linking words and phrases' },
      { label: 'Strong concluding statement or section' },
      { label: 'Correct grammar, capitalization, punctuation' },
      { label: 'Accurate spelling' },
    ] },

  // ─── WRITING: CONVENTIONS ONLY ───────────────────────────────────
  { name: 'Conventions Only', domain: 'writing', grades: [0],
    criteria: [
      { label: 'I write in a complete sentence' },
      { label: 'I use a capital letter to begin sentences and for "I"', standard: 'K.L.2a' },
      { label: 'I use ending punctuation', standard: 'K.L.2b' },
      { label: 'I can spell words phonetically', standard: 'K.L.2d' },
      { label: 'My writing is neat and letters are formed correctly', standard: 'K.L.1a' },
      { label: 'I have spaces between my words', standard: 'K.RF.1c' },
    ] },
  { name: 'Conventions Only', domain: 'writing', grades: [1, 2, 3, 4, 5],
    criteria: [
      { label: 'Complete sentences with correct grammar' },
      { label: 'Correct capitalization (sentences, names)' },
      { label: 'Correct ending punctuation' },
      { label: 'Accurate spelling using known patterns' },
      { label: 'Neat handwriting with proper spacing' },
    ] },

  // ─── READING RESPONSE ────────────────────────────────────────────
  { name: 'Reading Response (Basic)', domain: 'reading', grades: [0, 1],
    criteria: [
      { label: 'Writes at least one sentence about book' },
      { label: 'Sentence is relevant to story' },
      { label: 'Sentence is complete and makes sense' },
      { label: 'Uses best guess spelling' },
      { label: 'Uses accurate punctuation' },
      { label: 'Illustration matches words and is relevant' },
    ] },
  { name: 'Reading Response (Retelling)', domain: 'reading', grades: [1, 2],
    criteria: [
      { label: 'Includes events from beginning, middle, and end' },
      { label: 'Writes about key details from the book' },
      { label: 'Includes important characters' },
      { label: 'Uses known spelling patterns' },
      { label: 'Sentences are complete and make sense' },
    ] },
  { name: 'Reading Response (BME Retelling)', domain: 'reading', grades: [1, 2],
    criteria: [
      { label: 'Retells beginning of story' },
      { label: 'Retells middle of story' },
      { label: 'Retells end of story' },
      { label: 'Uses accurate punctuation and capital letters' },
      { label: 'Includes major characters' },
      { label: 'Includes temporal words to signal event order' },
    ] },
  { name: 'Reading Response (Problem/Solution)', domain: 'reading', grades: [1, 2, 3],
    criteria: [
      { label: 'Retells important events from story' },
      { label: 'Identifies problem and solution' },
      { label: 'Includes major characters in retell' },
      { label: 'Writing is easy to follow' },
      { label: 'Uses known spelling patterns' },
    ] },
  { name: 'Reading Response (Comprehensive)', domain: 'reading', grades: [2, 3],
    criteria: [
      { label: 'Accurately retells story with character names and events' },
      { label: 'Retells story in order' },
      { label: 'Sentences are complete and make sense' },
      { label: 'Uses appropriate punctuation and capitals' },
      { label: 'Writes sight words correctly and uses best guess spelling' },
      { label: 'Nice handwriting with spaces between words' },
      { label: 'Writes independently without extra teacher support' },
    ] },
  { name: 'Reading Response (Author\'s Purpose)', domain: 'reading', grades: [2, 3, 4, 5],
    criteria: [
      { label: 'Identifies author\'s purpose' },
      { label: 'Explains reasoning with evidence' },
      { label: 'Sentences are complete and make sense' },
      { label: 'Uses known spelling patterns' },
      { label: 'Correct capitalization and punctuation' },
    ] },
  { name: 'Reading Response (Character Analysis)', domain: 'reading', grades: [2, 3, 4, 5],
    criteria: [
      { label: 'Introduces character\'s name' },
      { label: 'Describes the character using identifying words' },
      { label: 'Gives story information relevant to character' },
      { label: 'Correct punctuation and capital letters' },
      { label: 'Uses known spelling patterns' },
      { label: 'Work is neat and organized' },
    ] },
  { name: 'Reading Response (Text Evidence)', domain: 'reading', grades: [3, 4, 5],
    criteria: [
      { label: 'Cites specific text evidence to support answer' },
      { label: 'Demonstrates thorough comprehension' },
      { label: 'Makes relevant connections to text' },
      { label: 'Complete, detailed response' },
      { label: 'Integrates vocabulary from text' },
    ] },

  // ─── SPEAKING ────────────────────────────────────────────────────
  { name: 'Oral Presentation', domain: 'speaking', grades: [1, 2, 3, 4, 5],
    criteria: [
      { label: 'Content is clear with supporting details' },
      { label: 'Speaks with appropriate volume and clarity' },
      { label: 'Makes eye contact with audience' },
      { label: 'Organized with beginning, middle, end' },
      { label: 'Uses complete sentences with varied language' },
    ] },
  { name: 'Partner Discussion', domain: 'speaking', grades: [1, 2, 3, 4, 5],
    criteria: [
      { label: 'Participates actively in discussion' },
      { label: 'Listens to partner and responds appropriately' },
      { label: 'Uses complete sentences' },
      { label: 'Stays on topic' },
      { label: 'Uses polite and respectful language' },
    ] },
]

export const LEVEL_LABELS = ['Needs Guidance', 'Developing', 'Meets Standards', 'Exceeds Standards']
export const LEVEL_COLORS = [
  'bg-red-100 text-red-700 border-red-300 ring-red-300',
  'bg-amber-100 text-amber-700 border-amber-300 ring-amber-300',
  'bg-green-100 text-green-700 border-green-300 ring-green-300',
  'bg-blue-100 text-blue-700 border-blue-300 ring-blue-300',
]
